import { Role, FitnessLevel } from './types';

export const TAG_DESCRIPTIONS: Record<string, string> = {
  'a': 'לוחמה',
  'c': 'פיקוד',
  'l': 'קבע',
  'd': 'מסוכן',
  't': 'טכנולוגי',
  's': 'חכם',
  'f': 'מעורב',
  'o': 'ימי',
  'g': 'צוות קטן',
  'h': 'פרוע',
  'x': 'מסווג',
  'n': 'ללא מיון'
};

// Database of combat roles
// S = High Intelligence requirement, T = High Technology requirement, A = High Combat intensity, G = Small/Elite Team
// H = Rowdy/Wild (Power Tag for bonus), F = Mixed
export const ROLES_DB: Role[] = [
  { id: 1, name: 'טיס', type: 'חיל האוויר', rank: 1, minProfile: 97, minDapr: 80, tags: 'alTSfGd', fitnessRequired: 2 },
  { id: 2, name: 'סיירת מטכ"ל', type: 'חיל היבשה', rank: 2, minProfile: 97, minDapr: 50, tags: 'Alsfgxd', fitnessRequired: 1 },
  { id: 3, name: 'שייטת 13', type: 'חיל הים', rank: 3, minProfile: 97, minDapr: 50, tags: 'Alsogxd', fitnessRequired: 1 },
  { id: 4, name: 'שלד"ג', type: 'חיל האוויר', rank: 4, minProfile: 97, minDapr: 50, tags: 'Altsgxd', fitnessRequired: 1 },
  { id: 5, name: 'לוחם 669', type: 'חיל האוויר', rank: 5, minProfile: 97, minDapr: 50, tags: 'Alfgd', fitnessRequired: 1 },
  { id: 6, name: 'חובלים', type: 'חיל הים', note: 'ייעודי לקצונה', rank: 6, minProfile: 82, minDapr: 60, tags: 'cltSfoG', fitnessRequired: 2 },
  { id: 7, name: 'שייטת 7 (צוללות)', type: 'חיל הים', rank: 7, minProfile: 82, minDapr: 60, tags: 'lTSoGx', fitnessRequired: 3 },
  { id: 8, name: 'מגלן', type: 'חיל היבשה', note: 'קומנדו', rank: 8, minProfile: 82, minDapr: 50, tags: 'Altsgd', fitnessRequired: 1 },
  { id: 9, name: 'דובדבן', type: 'חיל היבשה', note: 'קומנדו', rank: 9, minProfile: 82, minDapr: 50, tags: 'Alghxd', fitnessRequired: 1 },
  { id: 10, name: 'אגוז', type: 'חיל היבשה', note: 'קומנדו', rank: 10, minProfile: 82, minDapr: 50, tags: 'Alghxd', fitnessRequired: 1 },
  { id: 11, name: 'לוחם 504', type: 'חיל המודיעין', rank: 11, minProfile: 82, minDapr: 50, tags: 'atSGxd', fitnessRequired: 2 },
  { id: 12, name: 'לוחם קודקוד (קורל)', type: 'חיל האוויר', rank: 12, minProfile: 82, minDapr: 50, tags: 'TSGx', fitnessRequired: 2 },
  { id: 13, name: 'תוכנית ארז', type: 'חיל היבשה', note: 'ייעודי לקצונה', rank: 13, minProfile: 82, minDapr: 50, tags: 'aclGd', fitnessRequired: 2 },
  { id: 14, name: 'ימ"ס', type: 'חיל היבשה', rank: 14, minProfile: 82, minDapr: 30, tags: 'AgHxd', fitnessRequired: 1 },
  { id: 15, name: 'יהל"ם', type: 'חיל היבשה', rank: 15, minProfile: 82, minDapr: 30, tags: 'Atsfd', fitnessRequired: 2 },
  { id: 22, name: 'עוקץ', type: 'חיל היבשה', rank: 16, minProfile: 82, minDapr: 30, tags: 'AlfGd', fitnessRequired: 1 },
  { id: 16, name: 'סיירת צנחנים', type: 'חיל היבשה', rank: 17, minProfile: 82, minDapr: 40, tags: 'Ad', fitnessRequired: 1 },
  { id: 17, name: 'סיירת גולני', type: 'חיל היבשה', rank: 18, minProfile: 82, minDapr: 30, tags: 'AHd', fitnessRequired: 1 },
  { id: 19, name: 'סיירת גבעתי', type: 'חיל היבשה', rank: 19, minProfile: 82, minDapr: 30, tags: 'Ahd', fitnessRequired: 2 },
  { id: 18, name: 'סיירת נח"ל', type: 'חיל היבשה', rank: 20, minProfile: 82, minDapr: 30, tags: 'Ad', fitnessRequired: 2 },
  { id: 20, name: 'סיירת חרוב', type: 'חיל היבשה', rank: 21, minProfile: 82, minDapr: 30, tags: 'AHd', fitnessRequired: 2 },
  { id: 21, name: 'זיק - תותחנים', type: 'חיל היבשה', rank: 22, minProfile: 72, minDapr: 70, tags: 'TSfGx', fitnessRequired: 3 },
  { id: 23, name: 'רפאים', type: 'חיל היבשה', rank: 23, minProfile: 82, minDapr: 40, tags: 'atfg', fitnessRequired: 1 },
  { id: 24, name: 'יחידת הניוד 5515', type: 'חיל היבשה', rank: 24, minProfile: 82, minDapr: 30, tags: 'agxd', fitnessRequired: 2 },
  { id: 25, name: 'לוט"ר', type: 'חיל היבשה', rank: 25, minProfile: 82, minDapr: 50, tags: 'acfg', fitnessRequired: 2 },
  { id: 26, name: 'מיתר - תותחנים', type: 'חיל היבשה', rank: 26, minProfile: 72, minDapr: 50, tags: 'Tsfgx', fitnessRequired: 3 },
  { id: 27, name: 'מורן - תותחנים', type: 'חיל היבשה', rank: 27, minProfile: 72, minDapr: 50, tags: 'Tsfgx', fitnessRequired: 3 },
  { id: 56, name: 'מלא"ר - שריון', type: 'חיל היבשה', rank: 28, minProfile: 82, minDapr: 50, tags: 'aTsfg', fitnessRequired: 2 },
  { id: 28, name: 'רוכ"ש - תותחנים', type: 'חיל היבשה', rank: 29, minProfile: 82, minDapr: 50, tags: 'aTsfgd', fitnessRequired: 2 },
  { id: 29, name: 'ילת"ם', type: 'חיל הים', rank: 30, minProfile: 72, minDapr: 50, tags: 'tfoG', fitnessRequired: 2 },
  { id: 30, name: 'לוחם סנפיר', type: 'חיל הים', rank: 31, minProfile: 72, minDapr: 50, tags: 'foG', fitnessRequired: 2 },
  { id: 31, name: 'מודא"ל (מודיעין אלקטרוני)', type: 'חיל האוויר', rank: 32, minProfile: 72, minDapr: 50, tags: 'TSfGx', fitnessRequired: 3 },
  { id: 32, name: 'מפעיל ל"א', type: 'חיל האוויר', rank: 33, minProfile: 72, minDapr: 50, tags: 'TSfGx', fitnessRequired: 3 },
  { id: 33, name: 'קצין מודיעין טקטי', type: 'חיל המודיעין', note: 'ייעודי לקצונה', rank: 34, minProfile: 72, minDapr: 80, tags: 'cltSfGx', fitnessRequired: 3 },
  { id: 34, name: 'קשר"ג', type: 'חיל התקשוב', note: 'ייעודי לקצונה', rank: 35, minProfile: 72, minDapr: 60, tags: 'cltSfg', fitnessRequired: 3 },
  { id: 35, name: 'בז - שריון', type: 'חיל היבשה', note: 'ייעודי לקצונה', rank: 36, minProfile: 72, minDapr: 50, tags: 'Aclgd', fitnessRequired: 2 },
  { id: 36, name: 'מטאור - תותחנים', type: 'חיל היבשה', note: 'ייעודי לקצונה', rank: 37, minProfile: 82, minDapr: 50, tags: 'tsfgd', fitnessRequired: 2 },
  { id: 37, name: 'צנחנים', type: 'חיל היבשה', note: 'חי"ר', rank: 38, minProfile: 82, minDapr: 40, tags: 'Ad', fitnessRequired: 2 },
  { id: 38, name: 'גולני', type: 'חיל היבשה', note: 'חי"ר', rank: 39, minProfile: 82, minDapr: 30, tags: 'AHdn', fitnessRequired: 2 },
  { id: 39, name: 'גבעתי', type: 'חיל היבשה', note: 'חי"ר', rank: 40, minProfile: 82, minDapr: 30, tags: 'Ahdn', fitnessRequired: 2 },
  { id: 40, name: 'נח"ל', type: 'חיל היבשה', note: 'חי"ר', rank: 41, minProfile: 82, minDapr: 30, tags: 'Adn', fitnessRequired: 2 },
  { id: 41, name: 'כפיר', type: 'חיל היבשה', note: 'חי"ר', rank: 42, minProfile: 82, minDapr: 30, tags: 'AHdn', fitnessRequired: 2 },
  { id: 42, name: 'לוחם חוד ימי', type: 'חיל הים', rank: 43, minProfile: 72, minDapr: 30, tags: 'tfog', fitnessRequired: 3 },
  { id: 43, name: 'מג"ב', type: 'חיל היבשה', rank: 44, minProfile: 82, minDapr: 30, tags: 'afHdn', fitnessRequired: 2 },
  { id: 44, name: 'מנחית סער קדמי', type: 'חיל האוויר', rank: 45, minProfile: 82, minDapr: 50, tags: 'fg', fitnessRequired: 3 },
  { id: 45, name: 'יחידת הניוד 444', type: 'חיל היבשה', rank: 46, minProfile: 82, minDapr: 30, tags: 'gh', fitnessRequired: 3 },
  { id: 46, name: 'לוחמה אלקטרונית', type: 'חיל התקשוב', rank: 47, minProfile: 72, minDapr: 40, tags: 'tfx', fitnessRequired: 4 },
  { id: 47, name: 'הנדסה קרבית', type: 'חיל היבשה', rank: 48, minProfile: 82, minDapr: 40, tags: 'Atdn', fitnessRequired: 3 },
  { id: 48, name: 'שריון', type: 'חיל היבשה', rank: 49, minProfile: 72, minDapr: 40, tags: 'Atdn', fitnessRequired: 3 },
  { id: 49, name: 'תותחנים', type: 'חיל היבשה', rank: 50, minProfile: 72, minDapr: 40, tags: 'tfnf', fitnessRequired: 4 },
  { id: 50, name: 'מסייעת שריון', type: 'חיל היבשה', rank: 51, minProfile: 82, minDapr: 30, tags: 'Adn', fitnessRequired: 2 },
  { id: 51, name: 'הגנה אווירית', type: 'חיל היבשה', rank: 52, minProfile: 72, minDapr: 40, tags: 'Tfnf', fitnessRequired: 4 },
  { id: 52, name: 'איסוף קרבי', type: 'חיל היבשה', rank: 53, minProfile: 72, minDapr: 30, tags: 'tfnf', fitnessRequired: 4 },
  { id: 53, name: 'פלח"ץ (חילוץ והצלה)', type: 'חיל היבשה', rank: 54, minProfile: 72, minDapr: 30, tags: 'fhn', fitnessRequired: 4 },
  { id: 54, name: 'חי"ר גבולות', type: 'חיל היבשה', rank: 55, minProfile: 72, minDapr: 30, tags: 'fhn', fitnessRequired: 3 },
  { id: 55, name: 'לוחמה במעברים', type: 'חיל היבשה', rank: 56, minProfile: 72, minDapr: 30, tags: 'fhn', fitnessRequired: 4 },
];